package grpcbridge_test

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/peerrpc/go/grpcbridge"
	"github.com/peerrpc/go/peer"
	"github.com/peerrpc/go/rpc"
	"github.com/peerrpc/go/signal"

	"connectrpc.com/connect"
)

// TestBridge_BridgeIntoConnectHandler mounts a Connect HTTP handler
// behind a PeerRPC server. A PeerRPC client calls the bridged method
// and gets the Connect service's response back.
//
// The test uses a hand-rolled Connect handler that doubles its
// request payload — no codegen, no service. It demonstrates that
// standard Connect services (the ones generated by protoc-gen-
// connect-go) work through the bridge without modification.
func TestBridge_BridgeIntoConnectHandler(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// 1. Build the Connect service as a plain http.Handler. It
	//    doubles the request body and returns it.
	connectHandler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		body, _ := io.ReadAll(r.Body)
		w.Header().Set("Content-Type", "application/proto")
		_, _ = w.Write(append(append([]byte(nil), body...), body...))
	})

	// 2. Build the PeerRPC server with a bridge-mounted service.
	peerrpcSrv := rpc.NewServer()
	grpcbridge.MountConnectService(peerrpcSrv, "echo.Echo", []string{"Echo"},
		grpcbridge.HTTPHandlerInvoker{Handler: connectHandler},
	)

	// 3. Wire server + client through the in-process signaling
	//    backend so we exercise the real PeerRPC stack.
	backend := signal.NewLocal()
	oSig, _ := backend.Exchange(ctx, "room", "offerer")
	defer oSig.Close()
	aSig, _ := backend.Exchange(ctx, "room", "answerer")
	defer aSig.Close()

	oPeer, _ := peer.New(ctx, signal.RoleOfferer, peer.Config{})
	defer oPeer.Close()
	aPeer, _ := peer.New(ctx, signal.RoleAnswerer, peer.Config{})
	defer aPeer.Close()

	go func() {
		ch, err := aPeer.Accept(ctx, aSig)
		if err != nil {
			return
		}
		_ = peerrpcSrv.Serve(ctx, ch)
	}()

	och, err := oPeer.Dial(ctx, oSig)
	if err != nil {
		t.Fatalf("Dial: %v", err)
	}
	time.Sleep(100 * time.Millisecond)

	cli := rpc.NewClient(och)
	go cli.Attach(ctx)

	// 4. Issue the call: send "AB", expect "ABAB".
	resp, status := cli.InvokeUnary(ctx, "/echo.Echo/Echo", []byte("AB"), nil)
	if status.Code != 0 {
		t.Fatalf("status: %+v", status)
	}
	if !bytes.Equal(resp, []byte("ABAB")) {
		t.Fatalf("resp: %q want ABAB", resp)
	}
}

// touch unused imports to keep the linter quiet without forcing the
// test to depend on them via the bridge package's re-exports.
var (
	_ = connect.NewError
	_ = (*httptest.ResponseRecorder)(nil)
)
