[workspace]
members = ["protocol", "transport", "rpc", "peer", "signal"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
prost = "0.13"
bytes = "1"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
thiserror = "2"

peerrpc-protocol = { path = "protocol" }
peerrpc-transport = { path = "transport" }
peerrpc-signal = { path = "signal" }
