// Package protocol hosts the Phase-0 golden vector regression test.
//
// The vectors live in the repository at test/vectors/*.bin and are
// generated by cmd/gen-vectors. Every language SDK MUST decode these
// bytes identically and re-encode them to the exact same bytes.
//
// This Go test is the reference: it asserts the invariants below.
package protocol_test

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"

	peerrpcpb "github.com/peerrpc/go/gen/proto/peerrpc"
	"github.com/google/go-cmp/cmp"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

// vectorsDir resolves the test/vectors directory relative to the
// repository root (located via the buf.yaml marker).
func vectorsDir(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatalf("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	for i := 0; i < 12; i++ {
		if _, err := os.Stat(filepath.Join(dir, "buf.yaml")); err == nil {
			return filepath.Join(dir, "test", "vectors")
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("could not locate buf.yaml walking up from %s", file)
	return ""
}

// newMessageFor returns a freshly-allocated zero value of the proto
// message type expected for the given vector file. The mapping is
// derived from the vector name prefix.
func newMessageFor(t *testing.T, name string) proto.Message {
	t.Helper()
	switch {
	case strings.HasPrefix(name, "response_"):
		return &peerrpcpb.ResponseFrame{}
	case strings.HasPrefix(name, "frame_"):
		return &peerrpcpb.Frame{}
	default:
		t.Fatalf("unknown vector name prefix: %s", name)
	}
	return nil
}

// TestGoldenVectors_DecodeEncodeRoundTrip is the canonical Phase-0
// regression test. For every .bin in test/vectors:
//  1. Read the bytes.
//  2. Unmarshal into the appropriate Frame/ResponseFrame.
//  3. Re-marshal.
//  4. Assert byte-for-byte equality.
//
// Any drift in proto encoding (protobuf-go upgrade, schema change,
// non-determinism) fails here.
func TestGoldenVectors_DecodeEncodeRoundTrip(t *testing.T) {
	dir := vectorsDir(t)
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read vectors dir: %v", err)
	}

	var bins []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if filepath.Ext(name) != ".bin" {
			continue
		}
		bins = append(bins, strings.TrimSuffix(name, ".bin"))
	}
	sort.Strings(bins)

	if len(bins) < 10 {
		t.Fatalf("expected >=10 golden vectors, found %d (re-run cmd/gen-vectors)", len(bins))
	}

	for _, name := range bins {
		name := name
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(dir, name+".bin"))
			if err != nil {
				t.Fatalf("read %s.bin: %v", name, err)
			}
			msg := newMessageFor(t, name)
			if err := proto.Unmarshal(raw, msg); err != nil {
				t.Fatalf("unmarshal %s (%d bytes): %v", name, len(raw), err)
			}
			// Match the generator's mode: deterministic marshaling so
			// protobuf map iteration order does not flake the test.
			reencoded, err := (proto.MarshalOptions{Deterministic: true}).Marshal(msg)
			if err != nil {
				t.Fatalf("marshal %s: %v", name, err)
			}
			if len(reencoded) != len(raw) {
				t.Fatalf("%s size drift: original=%d reencoded=%d", name, len(raw), len(reencoded))
			}
			for i := range raw {
				if raw[i] != reencoded[i] {
					t.Fatalf("%s byte drift at offset %d: original=0x%02x reencoded=0x%02x",
						name, i, raw[i], reencoded[i])
				}
			}
		})
	}
}

// TestGoldenVectors_MatchesExpectedJSON verifies that each decoded
// vector matches its canonical description in expected.json. This is
// the cross-language comparison contract: every SDK does the same
// JSON-level check.
func TestGoldenVectors_MatchesExpectedJSON(t *testing.T) {
	dir := vectorsDir(t)
	raw, err := os.ReadFile(filepath.Join(dir, "expected.json"))
	if err != nil {
		t.Fatalf("read expected.json: %v", err)
	}
	var spec struct {
		Vectors map[string]struct {
			Size      int             `json:"size"`
			SHA256    string          `json:"sha256"`
			ProtoJSON json.RawMessage `json:"protojson"`
		} `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &spec); err != nil {
		t.Fatalf("unmarshal expected.json: %v", err)
	}

	for name, want := range spec.Vectors {
		name, want := name, want
		t.Run(name, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join(dir, name+".bin"))
			if err != nil {
				t.Fatalf("read %s.bin: %v", name, err)
			}
			if len(raw) != want.Size {
				t.Fatalf("%s size mismatch: file=%d expected=%d", name, len(raw), want.Size)
			}
			if got := sha256hex(raw); got != want.SHA256 {
				t.Fatalf("%s sha256 mismatch:\n got:  %s\n want: %s", name, got, want.SHA256)
			}

			msg := newMessageFor(t, name)
			if err := proto.Unmarshal(raw, msg); err != nil {
				t.Fatalf("unmarshal %s: %v", name, err)
			}
			got, err := protojson.Marshal(msg)
			if err != nil {
				t.Fatalf("marshal %s to json: %v", name, err)
			}
			// Compare in normalized object form (key ordering etc).
			var gotObj, wantObj any
			if err := json.Unmarshal(got, &gotObj); err != nil {
				t.Fatalf("normalize got: %v", err)
			}
			if err := json.Unmarshal(want.ProtoJSON, &wantObj); err != nil {
				t.Fatalf("normalize want: %v", err)
			}
			if diff := cmp.Diff(wantObj, gotObj); diff != "" {
				t.Fatalf("%s protojson drift (-want +got):\n%s", name, diff)
			}
		})
	}
}

// TestVectorCountGuaranteesMinimumSet sanity-checks that we have at
// least one vector exercising each oneof arm and each End truth-table
// row. Adding more vectors is fine; removing critical cases is not.
func TestVectorCountGuaranteesMinimumSet(t *testing.T) {
	required := []string{
		"frame_unary_call",
		"frame_unary_call_with_deadline",
		"frame_streaming_data_small",
		"frame_streaming_data_100k",
		"frame_chunked_data",
		"frame_end_close_send",
		"frame_end_cancelled",
		"response_begin_with_inline",
		"response_data_stream",
		"response_end_ok",
		"response_end_unavailable",
	}

	dir := vectorsDir(t)
	for _, name := range required {
		if _, err := os.Stat(filepath.Join(dir, name+".bin")); err != nil {
			t.Errorf("missing required vector %q: %v", name, err)
		}
	}
}

func sha256hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}
